# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FB_Tables

class DType(object):
    int8 = 0
    uint8 = 1
    int16 = 2
    uint16 = 3
    int32 = 4
    uint32 = 5
    float32 = 6
    float64 = 7
    c_string = 8

