# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FSD

import flatbuffers

class int32(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsint32(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = int32()
        x.Init(buf, n + offset)
        return x

    # int32
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # int32
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Int32Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 4))
        return 0

    # int32
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def int32Start(builder): builder.StartObject(1)
def int32AddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def int32StartValueVector(builder, numElems): return builder.StartVector(4, numElems, 4)
def int32End(builder): return builder.EndObject()
