# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FSD

class type(object):
    NONE = 0
    uint8 = 1
    int8 = 2
    uint16 = 3
    int16 = 4
    uint32 = 5
    int32 = 6
    uint64 = 7
    int64 = 8
    float32 = 9
    float64 = 10

