# automatically generated by the FlatBuffers compiler, do not modify

# namespace: FSD

import flatbuffers

class uint8(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsuint8(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = uint8()
        x.Init(buf, n + offset)
        return x

    # uint8
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # uint8
    def Value(self, j):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            a = self._tab.Vector(o)
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, a + flatbuffers.number_types.UOffsetTFlags.py_type(j * 1))
        return 0

    # uint8
    def ValueLength(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.VectorLen(o)
        return 0

def uint8Start(builder): builder.StartObject(1)
def uint8AddValue(builder, value): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(value), 0)
def uint8StartValueVector(builder, numElems): return builder.StartVector(1, numElems, 1)
def uint8End(builder): return builder.EndObject()
