# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class fwdinfo_2_t(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsfwdinfo_2_t(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = fwdinfo_2_t()
        x.Init(buf, n + offset)
        return x

    # fwdinfo_2_t
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # fwdinfo_2_t
    def SeqData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_2_t
    def SeqFwd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_2_t
    def TsData(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_2_t
    def TsFwd(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(10))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_2_t
    def Fwdix(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(12))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

    # fwdinfo_2_t
    def Teamid(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(14))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def fwdinfo_2_tStart(builder): builder.StartObject(6)
def fwdinfo_2_tAddSeqData(builder, seqData): builder.PrependUint64Slot(0, seqData, 0)
def fwdinfo_2_tAddSeqFwd(builder, seqFwd): builder.PrependUint64Slot(1, seqFwd, 0)
def fwdinfo_2_tAddTsData(builder, tsData): builder.PrependUint64Slot(2, tsData, 0)
def fwdinfo_2_tAddTsFwd(builder, tsFwd): builder.PrependUint64Slot(3, tsFwd, 0)
def fwdinfo_2_tAddFwdix(builder, fwdix): builder.PrependUint32Slot(4, fwdix, 0)
def fwdinfo_2_tAddTeamid(builder, teamid): builder.PrependUint64Slot(5, teamid, 0)
def fwdinfo_2_tEnd(builder): return builder.EndObject()
