# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarLong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarLong(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarLong()
        x.Init(buf, n + offset)
        return x

    # NTScalarLong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarLong
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int64Flags, o + self._tab.Pos)
        return 0

def NTScalarLongStart(builder): builder.StartObject(1)
def NTScalarLongAddValue(builder, value): builder.PrependInt64Slot(0, value, 0)
def NTScalarLongEnd(builder): return builder.EndObject()
