# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarUShort(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarUShort(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarUShort()
        x.Init(buf, n + offset)
        return x

    # NTScalarUShort
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarUShort
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint16Flags, o + self._tab.Pos)
        return 0

def NTScalarUShortStart(builder): builder.StartObject(1)
def NTScalarUShortAddValue(builder, value): builder.PrependUint16Slot(0, value, 0)
def NTScalarUShortEnd(builder): return builder.EndObject()
