# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarUByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarUByte(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarUByte()
        x.Init(buf, n + offset)
        return x

    # NTScalarUByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarUByte
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint8Flags, o + self._tab.Pos)
        return 0

def NTScalarUByteStart(builder): builder.StartObject(1)
def NTScalarUByteAddValue(builder, value): builder.PrependUint8Slot(0, value, 0)
def NTScalarUByteEnd(builder): return builder.EndObject()
