# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarFloat(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarFloat(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarFloat()
        x.Init(buf, n + offset)
        return x

    # NTScalarFloat
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarFloat
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def NTScalarFloatStart(builder): builder.StartObject(1)
def NTScalarFloatAddValue(builder, value): builder.PrependFloat32Slot(0, value, 0.0)
def NTScalarFloatEnd(builder): return builder.EndObject()
