# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarUInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarUInt(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarUInt()
        x.Init(buf, n + offset)
        return x

    # NTScalarUInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarUInt
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint32Flags, o + self._tab.Pos)
        return 0

def NTScalarUIntStart(builder): builder.StartObject(1)
def NTScalarUIntAddValue(builder, value): builder.PrependUint32Slot(0, value, 0)
def NTScalarUIntEnd(builder): return builder.EndObject()
