# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarULong(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarULong(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarULong()
        x.Init(buf, n + offset)
        return x

    # NTScalarULong
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarULong
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Uint64Flags, o + self._tab.Pos)
        return 0

def NTScalarULongStart(builder): builder.StartObject(1)
def NTScalarULongAddValue(builder, value): builder.PrependUint64Slot(0, value, 0)
def NTScalarULongEnd(builder): return builder.EndObject()
