# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarInt(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarInt(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarInt()
        x.Init(buf, n + offset)
        return x

    # NTScalarInt
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarInt
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int32Flags, o + self._tab.Pos)
        return 0

def NTScalarIntStart(builder): builder.StartObject(1)
def NTScalarIntAddValue(builder, value): builder.PrependInt32Slot(0, value, 0)
def NTScalarIntEnd(builder): return builder.EndObject()
