# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

import flatbuffers

class NTScalarByte(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAsNTScalarByte(cls, buf, offset):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = NTScalarByte()
        x.Init(buf, n + offset)
        return x

    # NTScalarByte
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # NTScalarByte
    def Value(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Int8Flags, o + self._tab.Pos)
        return 0

def NTScalarByteStart(builder): builder.StartObject(1)
def NTScalarByteAddValue(builder, value): builder.PrependInt8Slot(0, value, 0)
def NTScalarByteEnd(builder): return builder.EndObject()
