# automatically generated by the FlatBuffers compiler, do not modify

# namespace: f141_epics_nt

class PV(object):
    NONE = 0
    NTScalarByte = 1
    NTScalarUByte = 2
    NTScalarShort = 3
    NTScalarUShort = 4
    NTScalarInt = 5
    NTScalarUInt = 6
    NTScalarLong = 7
    NTScalarULong = 8
    NTScalarFloat = 9
    NTScalarDouble = 10
    NTScalarArrayByte = 11
    NTScalarArrayUByte = 12
    NTScalarArrayShort = 13
    NTScalarArrayUShort = 14
    NTScalarArrayInt = 15
    NTScalarArrayUInt = 16
    NTScalarArrayLong = 17
    NTScalarArrayULong = 18
    NTScalarArrayFloat = 19
    NTScalarArrayDouble = 20

